id: P000634
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-16 15:54:12.317275
source_metadata:
  id: bdr:W1KG25228
  title: ཡེ་ཤེས་ཀྱི་ཌཱ་ཀི་མ་ཇོ་མོ་ལབ་སྒྲོན་གྱི་རྣམ་ཐར་དང་བཀའ་ཚོམས་ཆེན་མོ་སོགས།
  author: ''
  volumes:
    6e5f23632340404a86baa7531b199f7b:
      image_group_id: I1KG25230
      title: ''
      volume_number: 1
      total_pages: 209
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
