id: IAD0DA7A9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T13:50:04+00:00'
last_modified: '2022-06-07T12:31:18.566967+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25228
  title: ཡེ་ཤེས་ཀྱི་ཌཱ་ཀི་མ་ཇོ་མོ་ལབ་སྒྲོན་གྱི་རྣམ་ཐར་དང་བཀའ་ཚོམས་ཆེན་མོ་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    794B:
      image_group_id: I1KG25230
      title: ''
      total_pages: 209
      order: 1
      base_file: 794B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
